### ISSUE TITLE
Required Vulkan extensions list contains empty strings

### ISSUE THREAD

**Issue by devvoid** [ForeverZer0/glfw-net#2]
When calling `GLFW.Vulkan.GetRequiredInstanceExtensions()`, multiple empty strings are included in the array. If you pass that to Vulkan and create an instance, it causes a crash. Using Linq to remove all empty strings makes it work as expected.

**Comment by ForeverZer0** [comment]
That's strange, not reproducible on my particular machine,  that scenario didn't occur to me.

I will make the edit and should it up within next few hours.

**Comment by ForeverZer0** [comment]
Got to it sooner than I thought I would. :-P

Fixed and updated NuGet package (still validating at the this exact moment).

**Comment by devvoid** [comment]
I feel like I didn't explain the issue correctly - it fails to output any genuine extension names at all for me; it creates an array of strings with a length of 2, but both entries are empty, whereas the GLFW source code says that (on Windows), it should contain `"VK_KHR_surface"` and `"VK_KHR_win32_surface"`. I can upload a minimal example of what I'm doing to see if that helps with reproducing the error.

**Comment by ForeverZer0** [comment]
Ah, found the bug. I had mistakenly used `Marshal.ReadInt32` instead of `Marshal.ReadIntPtr`, which obviously caused it to try and read a string from the wrong location. 

Fixed and tested, confirming it returns `"VK_KHR_surface"` and `"VK_KHR_win32_surface"` on my machine as well.

I apologize for the confusion. I have never worked with Vulkan, and as such the testing was pretty light in this area. If you encounter any other bugs with it, please let me know, I will get them fixed ASAP. The updated code is committed, will be updating NuGet package within the hour.

**Comment by devvoid** [comment]
The fix worked perfectly, the function now returns what you'd expect. Thanks!
