### ISSUE TITLE
KeyCallback handle throws AccessViolation

### ISSUE THREAD

**Issue by HuskyNator** [ForeverZer0/glfw-net#23]
AccessViolation is throw when dereferencing window handle from callback.
```csharp
unsafe public void keyCallback(IntPtr window, Keys key, int scanCode, InputState state, ModifierKeys mod) {
    if (state == InputState.Press) {
        switch (key) {
            case Keys.Escape:
                Glfw.SetWindowShouldClose( * (Window * ) window, true);
                //Glfw.SetWindowShouldClose(this.window, true); workaround-ish, does work.
                return;
            default:
                return; // Niets
        }
    }
}
```
I might be missing something basal here, yet i cannot figure it out. Have been using an instance variable as workaround.

**Comment by ForeverZer0** [comment]
I just created a similar scenario myself, and I agree it is rather unintuitive in its current state when used this way. At one point, I had changed all the static `Glfw` methods to use a `Window` instance instead of an `IntPtr`, but failed to also change the delegates. Being that there is no publicly exposed way to even cast an `IntPtr` to a `Window`, I definitely need to correct it.

I will get this fix corrected and uploaded pretty quickly, though it will unfortunately break some existing code with the prototype of the delegate being changed. Fixing it will be rather simple, but I hate to do that. Introducing an implicit cast or overload to temporarily for a few versions is probably not worth it, so it might just have to be inconvenience to deal with unless I come up with something else once the code is open in front of me.

**Comment by HuskyNator** [comment]
Oh okay, this actually comes as a relief to me, i was afraid i was doing something wrong,
I'm pretty new to c# so the whole IntPtr stuff kind of confuses me, including if/how casting works.
A personal workaround will be fine for now :), thanks for the swift reply

**Comment by ForeverZer0** [comment]
No, you are not using it incorrectly. The object-oriented `NativeWindow` way is the more traditional approach for C# users, which handles this for you, but I have purposefully exposed the lower-level static methods which would be more familiar to someone with knowledge of the base GLFW library and/or C. Since it is public, it should be more intuitive than it is, and be a proper analog of its C counterpart without any extra effort, so it's my fault.

I should be able to push out an updated release within the next day or so.
