### ISSUE TITLE
A callback was made on a garbage collected delegate of type 'GLFW.NET!GLFW.MouseCallback::Invoke'.

### ISSUE THREAD

**Issue by pozzer3** [ForeverZer0/glfw-net#36]
I am writing a very simple application based on the HelloTriangle, available at https://github.com/ForeverZer0/glfw-net on VisualStudio 2019. 

When I added some callbacks, I got the following error message: 

Process terminated. A callback was made on a garbage collected delegate of type 'GLFW.NET!GLFW.MouseCallback::Invoke'.
   at GLFW.Glfw.PollEvents()
   at GLFW.Glfw.PollEvents()
   at HelloTriangle.Program.Main(System.String[])

I've looked at "https://github.com/ForeverZer0/glfw-net/issues/19" and my code is very similar to your "solution 2". 

```
using System;
using System.IO;
using GLFW;
using static OpenGL.Gl;
using GlmNet;

namespace HelloTriangle
{
    class Program
    {
        static void Main(string[] args)
        {
            PrepareContext();
            Window window = CreateWindow(1500, 1500);
            var program = CreateProgram();

            var loc = glGetUniformLocation(program, "projectionMatrix");
            SetCallBacks(window);

            while (!Glfw.WindowShouldClose(window))
            {

                // Swap fore/back framebuffers, and poll for operating system events.
                Glfw.SwapBuffers(window);
                Glfw.PollEvents();

                int w, h;
                Glfw.GetFramebufferSize(window, out w, out h);  //this works properly. 
                glViewport(0, 0, w, h);

                glClear(GL_COLOR_BUFFER_BIT);

                mat4 mat = glm.ortho(0, w, h, 0);
                glUniformMatrix4fv(loc, 1, false, mat.to_array());
            }

            Glfw.Terminate();
        }

        private static void SetCallBacks(Window window)
        {
            Glfw.SetCursorPositionCallback(window, mouseHandler);  //MouseCallback
        }

        private static void mouseHandler(Window win, double x, double y)
        {
            Console.WriteLine("Mouse: " + x + "  " + y);
        }
       ....
}

====================================================

#version 330 core
layout (location = 0) in vec3 pos;
uniform mat4 projectionMatrix;
out vec2 TexCoord;

void main()
{
    TexCoord = uv;
    gl_Position = projectionMatrix * vec4(pos.x, pos.y, pos.z, 1.0);
}
```

====================================================

The application crashes after a few seconds. If I comment the command 

`glUniformMatrix4fv(loc, 1, false, mat.to_array());`

it runs a bit longer before crashing.

**Comment by ForeverZer0** [comment]
This part is the problem:

```
Glfw.SetCursorPositionCallback(window, mouseHandler);  //MouseCallback
```

This caused me a bit of issues too while I was creating the `NativeWindow` class, as it is not very apparent. Essentially, passing a method name directly as a delegate is just some syntatic sugar that C# implements, where it will automatically create an anonymous delegate for the specified method that you pass. The problem is that this anonymous delegate will get garbage collected, as the managed code thinks it is no longer referenced, even though it is in unmanaged code.

The solution is to explicitely set a delagte field containing the reference, which you can see examples of in [NativeWindow.cs](https://github.com/ForeverZer0/glfw-net/blob/master/GLFW.NET/NativeWindow.cs). The primary sections to look at are these parts:

Private fields the class uses:

```cs
        private PositionCallback windowPositionCallback;
        private SizeCallback windowSizeCallback, framebufferSizeCallback;
        private FocusCallback windowFocusCallback;
        private WindowCallback closeCallback, windowRefreshCallback;
        private FileDropCallback dropCallback;
        private MouseCallback cursorPositionCallback, scrollCallback;
        private MouseEnterCallback cursorEnterCallback;
        private MouseButtonCallback mouseButtonCallback;
        private CharModsCallback charModsCallback;
        private KeyCallback keyCallback;
        private WindowMaximizedCallback windowMaximizeCallback;
        private WindowContentsScaleCallback windowContentScaleCallback;
```

The method that creates refrences and stores them as member variables, so that a reference will exists for the lifetime of the object:

```cs

        private void BindCallbacks()
        {
            windowPositionCallback = (_, x, y) => OnPositionChanged(x, y);
            windowSizeCallback = (_, w, h) => OnSizeChanged(w, h);
            windowFocusCallback = (_, focusing) => OnFocusChanged(focusing);
            closeCallback = _ => OnClosing();
            dropCallback = (_, count, arrayPtr) => OnFileDrop(count, arrayPtr);
            cursorPositionCallback = (_, x, y) => OnMouseMove(x, y);
            cursorEnterCallback = (_, entering) => OnMouseEnter(entering);
            mouseButtonCallback = (_, button, state, mod) => OnMouseButton(button, state, mod);
            scrollCallback = (_, x, y) => OnMouseScroll(x, y);
            charModsCallback = (_, cp, mods) => OnCharacterInput(cp, mods);
            framebufferSizeCallback = (_, w, h) => OnFramebufferSizeChanged(w, h);
            windowRefreshCallback = _ => Refreshed?.Invoke(this, EventArgs.Empty);
            keyCallback = (_, key, code, state, mods) => OnKey(key, code, state, mods);
            windowMaximizeCallback = (_, maximized) => OnMaximizeChanged(maximized);
            windowContentScaleCallback = (_, x, y) => OnContentScaleChanged(x, y);

            Glfw.SetWindowPositionCallback(Window, windowPositionCallback);
            Glfw.SetWindowSizeCallback(Window, windowSizeCallback);
            Glfw.SetWindowFocusCallback(Window, windowFocusCallback);
            Glfw.SetCloseCallback(Window, closeCallback);
            Glfw.SetDropCallback(Window, dropCallback);
            Glfw.SetCursorPositionCallback(Window, cursorPositionCallback);
            Glfw.SetCursorEnterCallback(Window, cursorEnterCallback);
            Glfw.SetMouseButtonCallback(Window, mouseButtonCallback);
            Glfw.SetScrollCallback(Window, scrollCallback);
            Glfw.SetCharModsCallback(Window, charModsCallback);
            Glfw.SetFramebufferSizeCallback(Window, framebufferSizeCallback);
            Glfw.SetWindowRefreshCallback(Window, windowRefreshCallback);
            Glfw.SetKeyCallback(Window, keyCallback);
            Glfw.SetWindowMaximizeCallback(Window, windowMaximizeCallback);
            Glfw.SetWindowContentScaleCallback(Window, windowContentScaleCallback);
        }
```

**Comment by pozzer3** [comment]
Thank you a lot. It worked !!!

I suggest you to create one more example (extension of Hello Triangle) including:
1 - This callback handling
2 - Code to handle Shading Compiler Error 
     
 ```
private static uint CreateShader(int type, string source)
{
      var shader = glCreateShader(type);
      glShaderSource(shader, source);
      glCompileShader(shader);
      string s = glGetShaderInfoLog(shader);
      if (!string.IsNullOrWhiteSpace(s))
      {
          Console.WriteLine(s);
      }
      return shader;
}
```

3 - A more complex primitive. I took a lot of time to notice that 
 ```
 glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, vboID[2]);
```
doesn't work with 

 ```
glDrawElements(GL_TRIANGLES, indices); 
 ```

and that the best way is to use, for instance: 
   ```
 glDrawArrays(GL_TRIANGLE_STRIP, 0, numVert); 
 glDrawArrays(GL_LINE_LOOP, 0, numVert);
```
with no index array.

**Comment by ForeverZer0** [comment]
I agree about clarifying callback handling, will definitey take that into account and likely expand on that in the documentation and/or the wiki when I get around to it.

As for the OpenGL logic in the example, that is a bit outside the scope of the this project. The bindings themselves really shouldn't be used in any production code, and were generated from a hand-made script using the Khronos registry. They were not even checked extensively for correctness, just quick overlook and a few edits for ease-of-use. If you choose to use them, be sure to double-check the correctness of any methods you may be using, I would be surprised if there wasn't at least one or two functions that are incorrect with an in/out of a pointer, etc. I just wanted to supply a some bare-bones OpenGL code that could be used for testing the GLFW library that didn't require dependencies on another package.

I have since created better bindings for a personal project, more complete, taking advantage of C# language constructs, like strongly-typed enums, naming conventions, overloads, etc. I perhaps may include this or package it and release as a compliment to this one for those of us who like to start with the minimal bindings, and not have it abstracted away with full-fledged game engines, etc.

**Comment by pozzer3** [comment]
Thank you again. I'm not so fluent on bindings and C# to code something more robust than your implementation. I'll continue using it as it is. Thanks.
