### ISSUE TITLE
BadImageFormatException on .NET framework 4.7.2 via NuGet and source

### ISSUE THREAD

**Issue by Arthour** [ForeverZer0/glfw-net#37]
Yesterday and today I tried to get your library to run (first via NuGet, later on also via the source from here).
I first tried to use .NET framework 4.7.2 which always resulted in either a DllNotFoundException (due to wrong naming, wrong location and forgetting to copy the dll to the output) and BadImageFormatException, which I could not resolve - this seems to be a problem with .NET framework (occured both via NuGet and your source, using the same dll file that worked with your example).
When I tried to use .NET Core 3.1 it worked fine with the NuGet version as soon as I had setup the dll correctly.

Also maybe you could improve the usability by
- making the LIBRARY path changeable (especially for the NuGet version)
- extending the Getting Started part in the README (state where exactly the dll should be put in and which name it should have, in the best case also mention to not forget setting the copy to source option in the IDE)
- adding a troubleshooting part to the README containing the more common exceptions

This especially the README would probably resolve most errors

**Comment by ForeverZer0** [comment]
A `BadImageFormatException` is just a mismatch of CPU architecture and the native DLL architecture, and likely due to what .NET Framework defaults to when building under `AnyCPU` compared to how .NET Core does it, though I can't say with certainty without checking the documentation first. 

The most robust solution that is guaranteed to work with any .NET implementation and supported platform is to explicitely specify x86 and x64 builds, and distribute the respective native DLL along with each. 

Realistically speaking, unless you plan to support old hardware, there is little reason to bother with x86 anymore, just build for x64 and call it done. Windows is the only system that this issue would even be applicable for, and they stopped supporting any system with x86 a while back.

**Comment by Arthour** [comment]
Ah, well!

I almost was about to tell you that I already used x64, but just about now I remembered that I set x64 for my main project but not for the test project I set up to test you lib.

Changed that to specifically target x64 and it's now working fine with .NET framework 4.7.2 too!

Thanks!
