### ISSUE TITLE
Application crashes when running on x86

### ISSUE THREAD

**Issue by pozzer3** [ForeverZer0/glfw-net#38]
I've downloaded Glfw-net and started developing my application using "Any CPU" configuration on Windows 10, based on the HelloTriangle demo. I've downloaded glfw.dll from https://www.glfw.org/. 

Since I have plans to run my application on x86 platforms, I've changed the configuration to "x86" on Visual Studio 19 (Version 16.8.2). I've downloaded the glfw.dll for x86 architecture. In this configuration, the application crashes immediately.  

Sometimes, it reports Error 0xc0000005 (Access Violation) and (process 17684) exited with code -1073740791. I also tried different versions of glfw.dll, but with no success. 

After hundreds of unsuccessful experiments, I returned to the HelloTriangle demo to compare to it with my application (HelloTrinagle runs smoothly on x86 and x64). I was considering the problem could be related to texture loading, shaders, and so on. 

I've started adding code to the HelloTriangle (code used on my application) to try to find the error. I noticed that just adding something like this  

   ```
     mat4 matOrtho = glm.ortho(0, 500, 500, 0);
     glUniformMatrix4fv(projectionMatrixLoc, 1, false, matOrtho.to_array());
```
or 
```
      v = new float[100];
```

to the render loop causes the application to crash. In other words, anything that allocates some memory. The larger the memory block, the faster the failure occurs. 

 ```
           while (!Glfw.WindowShouldClose(window))
            {
                Glfw.SwapBuffers(window);
                Glfw.PollEvents();

                //mat4 matOrtho = glm.ortho(0, 500, 500, 0);
                //glUniformMatrix4fv(projectionMatrixLoc, 1, false, matOrtho.to_array());
                //v = new float[1000];

                glClear(GL_COLOR_BUFFER_BIT);
                glDrawArrays(GL_TRIANGLES, 0, 3);
            }
```

Since my application loads several textures, in x86 it crashes even before the render loop is reached.

**Comment by ForeverZer0** [comment]
Would it be possible to provide some minimal example? It is difficult to tell based on the information and limited code example. 

If you happen to be using the the OpenGL class supplied in the example, do bear in mind that is for example use only, and all but a portion of it just generated from the Khronos registry using a custom script. Although your issue seems to not be directly related, I would strongly suggest to check it for correctness before using it, as I a cannot recall ATM if it even checks for missing symbols when importing OpenGL. 

Your problem does have me scratching my head though, and I am not exactly sure what the problem as stated. I am not sure how the GLM library you use is allocates memory, but GLFW does not use any custom memory allocation (even natively). It is doubly confusing as I would not expect an `AccessViolationException` in either case, but perhaps a `StackOverflowException` or `OutOfMemoryException` if indeed related to allocation. 

`AccessViolationException` could indicate a few different things, some of them much different, so we might need to dig a bit deeper before tracking down the exact cause of the error.

Some possible quick things to confirm might help narrow it down:

* Ensure that the delegate `glUniformMatrix4fv` is trying to call is not `null` (it is simply `_glUniformMatrix4fv` if memory serves...). All of the GL functions are just simple wrapper around a delegate that is set at runtime using `Marshal.GetDelegateForFunctionPointer`. If it failed to find the entry point, and it was not accounted for, it would cause that exception when trying to invoke an OpenGL function. My hunch is that this is the problem, though my confusion is that said memory allocation fails, not the OpenGL function call, unless I misunderstood.
* Try moving the function that allocates the memory every frame to a separate method. It is possible that is repeatedly allocating more and more memory, and it is never freed as the context stays within the same loop. I would have expected a `StackOverflowException` in that situation, or a `OutOfMemoryException`, but I don't profess to know how the C# internally handles garbage collection, and/or marshalling a value type when it failed to create it. I would expect an exception, but it might help narrow it down. Separating the possible points of failure into different places would help indicate what area is failing.

```csharp
/// <summary>
/// Specify the value of a uniform variable for the current program object.
/// </summary>
/// <param name="location">Specifies the location of the uniform variable to be modified.</param>
/// <param name="count">Specifies the number of matrices that are to be modified.</param>
/// <param name="transpose">Specifies whether to transpose the matrix as the values are loaded into the uniform variable.</param>
/// <param name="values">An array of count values that will be used to update the specified uniform variable.</param>
public static void glUniformMatrix4fv(int location, int count, bool transpose, [NotNull] float[] values)
{
    if (_glUniformMatrix4fv is null)
        throw new Exception("This is the problem, the OpenGL entry point is not being found in the native library");
    fixed (float* value = &values[0]) 
    {
        _glUniformMatrix4fv(location, count, transpose, value);
    }
}
```

**Comment by pozzer3** [comment]
I've made some experiment to try to locate the problem.

I'm running the HelloTriangle example (from your repository), and added the Malloc( ) function to the render Loop, without any other modification, just to simulate some memory allocation, that in fact is similar to call mat4 matOrtho = glm.ortho(0, 500, 500, 0) to update the projection matrix. I'm not using any other delegate function (just the one present in your demo -> SetRandomColor), and the problem happens on both NET core 3.1 or NET 5.0, but just in the x86 configuration. 


            while (!Glfw.WindowShouldClose(window))
            {
                Glfw.SwapBuffers(window);
                Glfw.PollEvents();

                Malloc(); //------>>>>>>>>This is my new Code to emulate small memory allocation. 

                glClear(GL_COLOR_BUFFER_BIT);
                if (n++ % 60 == 0)
                    SetRandomColor(location);
                glDrawArrays(GL_TRIANGLES, 0, 3);
            }

        static void Malloc()
        {
            try
            {
                float[] v1 = new float[1000];
                //Console.Write("x");
            }
            catch (AccessViolationException e)
            {
                Console.WriteLine("AccessViolationException");
            }
            catch (StackOverflowException e)
            {
                Console.WriteLine("StackOverflowException");
            }
            catch (OutOfMemoryException e)
            {
                Console.WriteLine("OutOfMemoryException");
            }
            catch (System.Exception e)
            {
                Console.WriteLine("Exception");
            }
        }

The loop runs 1258 times before crashing, that means more or less 5 MB of memory space. No exception is invoked. 

If I call Malloc() outside the Glfw loop, it crashes in the same way, after 1261 iterations.  

            while (true)
            {
                Malloc();
            }

            while (!Glfw.WindowShouldClose(window))
            {
                Glfw.SwapBuffers(window);
                Glfw.PollEvents();
                 .....
          }

If I comment the CreateProgram(), than it runs forever. 

        static void Main(string[] args)
        {
            PrepareContext();
            var window = CreateWindow(1024, 800);
            //var program = CreateProgram();  //-------------->>>>>>>>>>>>>comment this line

            while (true)
            {
                Malloc();
            }
      }

From these examples, it seems that "OpenGL" is limiting the available memory. In my real application, after loading some textures, the app crashes, even before reaching the render loop.

**Comment by ForeverZer0** [comment]
From the sounds of it, the GC is just not keeping up with freeing the amount of memory allocations, but why this would only have an effect in an x86 build is very puzzling. Neither OpenGL nor GLFW do any memory allocations, at least as part of their external API, and leave it to higher-level applications (this is by design). 

Allocating memory as you are doing is obviously not the ideal way to do it, but I would expect it to still "work", not fail -- and only on one CPU architecture. My current system is not setup to test x86-only properly, I am on a Linux OS that doesn't use seperate x86 and x64 libraries to load, there is only x86_x64. I have been intending to get a Windows partition setup for testing, wil get that done today to see if I can help diagnose this problem.

**Comment by pozzer3** [comment]
I've used that kind of memory allocation just to have a tinny source code to crash de application. It took me days to discover that the problem was with the memory (at least it looks like memory is crashing the app). In my real application I have a class to manage all the textures using a Dictionary to avoid duplicating textures on RAM.  I'm developing a pneumatic simulator. Hope you can diagnose the problem. 
![image](https://user-images.githubusercontent.com/8484030/103942352-04186900-510f-11eb-9abb-c0de6793f198.png)

**Comment by ForeverZer0** [comment]
Nice screenshot, though admittedly pneumatics is definitely a subject I know very little about xD. 

I thought of one possibility that may also be occurring, as it is uncommon and would only occasionally show itself in long-running methods, especially ones that allocated memory, which yours *may* qualify. See [this MSDN page](https://docs.microsoft.com/en-us/dotnet/api/system.gc.keepalive?view=net-5.0) for an example and description that explains it better than I could.

> The purpose of the KeepAlive method is to ensure the existence of a reference to an object that is at risk of being prematurely reclaimed by the garbage collector. A common scenario where this might happen is when there are no references to the object in managed code or data, but the object is still in use in unmanaged code such as Windows APIs, unmanaged DLLs, or methods using COM.

Essentially, just because a variable is defined "higher-up" in a method, it is not safe from garbage collection just because the method has not yet returned (i.e. control flow has moved to a loop within it). If the method is still running while the GC starts, C# may see that a variable is no longer referenced later in the method, and determine that it is eligible for garbage collection. When dealing with objects that are really just wrappers around unmanaged ones (i.e. the OpenGL context), it could cause some mayhem. Not sure if this applies to your project, but might be one other possible thing to look for.

**Comment by pozzer3** [comment]
I've created the tiniest program that crashes on x86. It doesn't have long-running methods, so GC may not affect it. Line 54 (glShaderSource(shader, source);) is apparently causing the problem. If I remove that line, the app runs and finishes Successfully. 

```
using System;
using System.IO;
using GLFW;
using static OpenGL.Gl;

namespace HelloTriangle
{
    class Program
    {
        static void Main(string[] args)
        {
            var window = CreateWindow(1024, 500);
            var program = CreateProgram();

            for (int i = 0; i < 2000; i++)   //------>>>>> This runs fine before CreateProgram() ------------>
            {
                float[] v = new float[1000];
            }
            Console.WriteLine("Success.....");
        }


        private static Window CreateWindow(int width, int height)
        {
            var window = Glfw.CreateWindow(width, height, "Hello Triangle!", Monitor.None, Window.None);
            Glfw.MakeContextCurrent(window);
            Import(Glfw.GetProcAddress);
            return window;
        }

        private static uint CreateProgram()
        {
            var vertex = CreateShader(GL_VERTEX_SHADER, File.ReadAllText("./triangle.vert"));
            var fragment = CreateShader(GL_FRAGMENT_SHADER, File.ReadAllText("./triangle.frag"));

            var program = glCreateProgram();
            glAttachShader(program, vertex);
            glAttachShader(program, fragment);

            glLinkProgram(program);

            glDeleteShader(vertex);
            glDeleteShader(fragment);

            glUseProgram(program);
            return program;
        }

        private static uint CreateShader(int type, string source)
        {
            var shader = glCreateShader(type);
            glShaderSource(shader, source);  //--------->>>>>>>>>>> Here is the line. ----------------->>>>>>>>
            glCompileShader(shader);
            return shader;
        }
    }
}
```

Vertex and Fragment programs

```
#version 330   
void main()
{
} 

#version 330 
void main()
{
}
```

**Comment by ForeverZer0** [comment]
I likely de-referenced pointer in that function incorrectly, the native GL analog for that function is rather awkward. Combining that with unsafe and pointers in C# using fixed statements, and it starts to get ugly.

The OpenGL bindings aren't really part of the project, but I will update them sometime with another version I had made that were much more robust and user-friendly. 

In the meantime, to address the actual problem, you can edit the function (and delegate) to resemble this:

```csharp
// The delgate that actually gets called
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
private delegate void PFNGLSHADERSOURCEPROC(uint shader, int count, /*const*/ IntPtr[] str, /*const*/ int[] length);

public static void glShaderSource(uint shader, int count, /*const*/ IntPtr[] str, /*const*/ int[] length) => _glShaderSource(shader, count, str, length);

public static void glShaderSource(uint shader, [NotNull] string source)
{
    var utf8 = Encoding.UTF8.GetBytes(source);

    var handle = GCHandle.Alloc(utf8, GCHandleType.Pinned);
    var sources = new[] { handle.AddrOfPinnedObject() };
    var lengths = new[] { utf8.Length };

    _glShaderSource(shader, 1, sources, lengths);
    handle.Free();
}
```

In my many years of using OpenGL, I have never once encountered a reason to ever need to pass multiple source strings to a single shader unit, so not sure why Khronos chose to design the interface as such,. This function is annoying to use even when writing native C code where you don't need to do any Marshalling, but I digress, I will stop ranting :P

**Comment by pozzer3** [comment]
Still not working. App crash in the same way. I've updated the OpenGl.cs with your new code. In x64 it still works with the new code.

**Comment by ForeverZer0** [comment]
Hmm, I am running out of ideas. I am sure 100% certain that the C# function is wrapped correctly (as indicated it working on x64), and from that point on it is all managed by the runtime and native libraries. There is nothing in the wrapper method that would make it fail on x86.

This would only leave a few edge cases left, none of which seem likely:

* The .NET runtime is marshalling it incorrectly (**extremely** unlikely)
* The x86 OpenGL drivers have a bug (i.e. NVIDIA, AMD, etc). This is not unheard of, and compounded with being a depreciated architecture, but it is going to be very difficult to pin it down to this. 
* Incompatible drivers are installed for x86. Pretty unlikely, most vendors simply ship both architectures together as a single installation that is transparent to the user.
* The wrong OpenGL library is being referenced by the native GLFW library. I checked all the tickets over there, was unable to find similar/related issues. Linking to the correct GL on Windows can actually be non-trivial. I would suspect that even a basic `glClear` would cause the same error if this was the case though. If it was linking only to the 1.1 version that ships with Windows, the `glCreateShader` call would fail before `glShaderSource`, as that function does not exist in the old legacy version either.

Could you sprinkle a slew of `Glfw.GetError` and `GL.GetError` calls all over the place to see if there is something we are overlooking?

**Comment by TheBoneJarmer** [comment]
Perhaps I can be of any assistance. I once had a similar issue where the window refused to open at all. Crashed right away with a similar error code.  Do you happen to have a combination of an nvidia graphics card along with an intel graphics card?

Also, have you tried other pre-compiled dll files from the GLFW downloads page? I use the one from MINGW64 because the one for VC didn't work.

**Comment by ForeverZer0** [comment]
Closed due to inactivity.
