### ISSUE TITLE
GLFW Keeps calling Garbage Collected Fields

### ISSUE THREAD

**Issue by JahleelAbraham** [ForeverZer0/glfw-net#44]
Im not sure if this is just me being dumb or not however i keep encountering this error when enough event callbacks are called

Error:
```
Process terminated. A callback was made on a garbage collected delegate of type 'JStudio!GLFW.MouseCallback::Invoke'.
Repeat 2 times:
--------------------------------
   at GLFW.Glfw.PollEvents()
--------------------------------
   at TheJYT.JStudio.Platform.Windows.WindowsWindow.OnUpdate()
   at TheJYT.JStudio.Application.Run()
   at TheJYT.JStudio.Studio.Main()
   at TheJYT.JStudio.Sandbox.Program.Main(System.String[])
```

This error only occures when enough event callbacks trigger.

Let me know if you need anything else

**Comment by ForeverZer0** [comment]
This sounds like it is similar issue to #36, which is simply a hidden pitfall with some syntatic sugar C# uses with delegate types in unmanaged code.

This is going to occur when you directly use the static `Glfw` class and do something such as this:

```csharp
private static void OnWindowMove(IntPtr window, int x, int y)
{
    // Execute some stuff when window position is moved...
}

private static void SetCallbacks(IntPtr window)
{
    Glfw.SetWindowPosCallback(window, OnWindowMove);
}
```

There is a hidden "gotcha" in this code that will cause problems with the GC, and it is not immediately apparent as it will only happen when using delegate callbacks with unmanaged code. When you do this:

```csharp
Glfw.SetWindowPosCallback(window, OnWindowMove);
```

...you are actually doing this, but the language runtime simply allows you to do it the shorthand method:

```csharp
Glfw.SetWindowPosCallback(window, new WindowPosCallback(OnWindowMove));
```

As you can see, there is a delegate instance being created there, you are not actually directly sending a function pointer to the unmanaged method, it is just occurring automatically for you. Under normal circumstances with managed code, this is not a problem, the runtime is aware of the reference count for that auto-delegate, and it will not be collected by the GC.

Since this is unmanaged code, you have created a delegate, and as far as the managed runtime is concerned, it is not being assigned to anything, and no reference exists for it, so the GC thinks it is fair game to be collected during the next pass, not aware that it is still being used in unmanaged code.

The solution is pretty simple, and you can see an example how it is done in the [NativeWindow.cs](https://github.com/ForeverZer0/glfw-net/blob/master/GLFW.NET/NativeWindow.cs) file: Create a delegate manually and maintain your own reference (i.e. a variable) then pass in that delegate to the method.

```csharp
private static WindowPosCallback posCallback = new WindowPosCallback(OnWindowMove);

private static void OnWindowMove(IntPtr window, int x, int y)
{
    // Execute some stuff when window position is moved...
}

private static void SetCallbacks(IntPtr window)
{
    Glfw.SetWindowPosCallback(window, posCallback);
}
```

The `NativeWindow` class handles this automatically for you if an OOP approach is a viable solution for your project. It is a lightweight wrapper around using the static `Glfw` directly, which solves some of these little idiosyncrasies transparently, and do things more in the "C# way".

**Comment by JahleelAbraham** [comment]
Yea i figured out the same thing about 5 mins after posting. So sorry. Thanks for taking the time to respond and making a couple of questions more clear!
