### ISSUE TITLE
Resizing Problem when using Skia

### ISSUE THREAD

**Issue by sawcce** [ForeverZer0/glfw-net#45]
For some unknown reason, when using the skia example, resizing the window doesn't actually seem to resize the canvas.
Instead, the dimensions stay the same and the canvas is docked in the bottom left corner of the screen

# Information

    <PackageReference Include="SkiaSharp" Version="2.80.3" />
    <PackageReference Include="glfw-net" Version="3.3.1" />

Windows 10

**Comment by ForeverZer0** [comment]
I am not very familiar with the Skia, but I would assume that no backend rendering API is going to automatically change its canvas size when the window changes. In OpenGL, it will automatically change the backbuffer sizes, but it is still the responsibility of the user to account for this change (i.e. projection/view matrix). 

Since a Skia canvas is an abstraction over this, it is likely necessary to use the window buffer's resize callback to update the canvas size as needed. I am inexperienced with Skia to give the exact tested code, but the example project has code on how to create the canvas that should hopefully provide a starting point.

**Comment by sawcce** [comment]
> I am not very familiar with the Skia, but I would assume that no backend rendering API is going to automatically change its canvas size when the window changes. In OpenGL, it will automatically change the backbuffer sizes, but it is still the responsibility of the user to account for this change (i.e. projection/view matrix).
> 
> Since a Skia canvas is an abstraction over this, it is likely necessary to use the window buffer's resize callback to update the canvas size as needed. I am inexperienced with Skia to give the exact tested code, but the example project has code on how to create the canvas that should hopefully provide a starting point.

Thanks, I'm gonna try to debug it more and hopefully find a solution!
To be honest I still don't know why the example in this repo doesn't work for me, but I'll guess I'll have to figure it out

**Comment by sawcce** [comment]
I actually found a fix to my problem 
```csharp
        private static void OnWindowsSizeChanged(object sender, SizeChangeEventArgs e)
        {
            skiaSurface = GenerateSkiaSurface(context, e.Size);
            canvas = skiaSurface.Canvas;
            Program.Render();
        }
```
It might not be optimized but it works 🤷🏻

**Comment by ForeverZer0** [comment]
Glad you found a solution.

You can check the Skia API to see if there are functions for canvas resizing, but otherwise re-creating it is probably the only solution left. I would have to double-check, but I believe the resize event only fires once when resizing is complete, not for every minor change during resize. If that is the case, that would make it not be anything to be too concerned about as far as optimization, as window resizing is not something a user is going to be doing constantly during program execution.
